name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
